const ADD_CARD = '@@cards/ADD_CARD';
const EDIT_CARD = '@@cards/ADD_CARD';
const REMOVE_CARD = '@@cards/REMOVE_CARD';
const FETCH_CARDS_SUCCESS = '@@cards/FETCH_CARDS_SUCCESS';
const FETCH_CARD_SUCCESS = '@@cards/FETCH_CARD_SUCCESS';
const FETCH_TEMP_CARD_SUCCESS = '@@cards/FETCH_TEMP_CARD_SUCCESS';
const DELETE_TEMP_CARDS = '@@cards/DELETE_TEMP_CARDS';

export {
    ADD_CARD,
    EDIT_CARD,
    REMOVE_CARD,
    FETCH_CARDS_SUCCESS,
    FETCH_CARD_SUCCESS,
    FETCH_TEMP_CARD_SUCCESS,
    DELETE_TEMP_CARDS
};

