const LOGIN_REQUEST = '@@auth/LOGIN_REQUEST';
const LOGIN_SUCCESS = '@@auth/LOGIN_SUCCESS';
const LOGIN_ERROR = '@@auth/LOGIN_ERROR';

const SIGN_UP_REQUEST = '@@auth/SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = '@@auth/SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = '@@auth/SIGN_UP_ERROR';

const LOGOUT = '@@auth/LOGOUT';


export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    SIGN_UP_REQUEST,
    SIGN_UP_SUCCESS,
    LOGOUT
};
