const ADD_POST = {
    REQUEST: '@@posts/ADD_POST_REQUEST',
    SUCCESS: '@@posts/ADD_POST_SUCCESS',
    ERROR: '@@posts/ADD_POST_ERROR'
};

const EDIT_POST = {
    REQUEST: '@@posts/EDIT_POST_REQUEST',
    SUCCESS: '@@posts/EDIT_POST_SUCCESS',
    ERROR: '@@posts/EDIT_POST_ERROR'
};

const REMOVE_POST = {
    REQUEST: '@@posts/REMOVE_POST_REQUEST',
    SUCCESS: '@@posts/REMOVE_POST_SUCCESS',
    ERROR: '@@posts/REMOVE_POST_ERROR'
};

const FETCH_POSTS = {
    REQUEST: '@@posts/FETCH_POSTS_REQUEST',
    SUCCESS: '@@posts/FETCH_POSTS_SUCCESS',
    ERROR: '@@posts/FETCH_POSTS_ERROR'
};

const FETCH_POST = {
    REQUEST: '@@posts/FETCH_POST_REQUEST',
    SUCCESS: '@@posts/FETCH_POST_SUCCESS',
    ERROR: '@@posts/FETCH_POST_ERROR'
};

const TOGGLE_LIKE = {
    REQUEST: '@@posts/TOGGLE_LIKE_REQUEST',
    SUCCESS: '@@posts/TOGGLE_LIKE_SUCCESS',
    ERROR: '@@posts/TOGGLE_LIKE_ERROR'
};

const SELECT_PAGE = '@@posts/SELECT_PAGE';

const RESET_STATUS = {
    FETCH_POSTS: '@@posts/RESET_FETCH_POSTS_STATUS',
    FETCH_POST: '@@posts/RESET_FETCH_POST_STATUS',
    ADD_POST: '@@posts/RESET_ADD_POST_STATUS',
    EDIT_POST: '@@posts/RESET_EDIT_POST_STATUS',
    REMOVE_POST: '@@posts/RESET_REMOVE_POST_STATUS',
    TOGGLE_LIKE: '@@posts/RESET_TOGGLE_LIKE_STATUS'
};

export {
    ADD_POST,
    EDIT_POST,
    REMOVE_POST,
    FETCH_POSTS,
    FETCH_POST,
    TOGGLE_LIKE,
    RESET_STATUS,
    SELECT_PAGE
};

